# Importing some important libraries 


In [1]:
import numpy as np #importing numpy with alias 'np' for using numpy based array which are optimized for calculations
import matplotlib.pyplot as plt #importing matplotlib library with alias 'plt' which is used for plotting the graph
from sklearn.linear_model import LinearRegression #importing sklearn library that is used for linear regression


### Creating a training data sets : Input data
#### x as features or independent variable
#### y as label or dependent variable

In [18]:
x = [1,2,3,4,5] 

In [19]:
y = [4,8,12,16,20]

### Converting an array to numpy array

In [4]:
x_np = np.array(x)

In [5]:
print(x_np)

[1 2 3 4 5]


In [6]:
y_np = np.array(y)

In [7]:
print(y_np)

[ 4  8 12 16 20]


### An array with structure (n, ) is rank 1 array

In [8]:
x_np.shape

(5,)

In [9]:
y_np.shape

(5,)

### Converting rank 1 array to 1d column vector


In [10]:
x_np_col = x_np.reshape(-1, 1)

In [11]:
print(x_np_col)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
x_np_col.shape

(5, 1)

In [13]:
y_np_col = y_np.reshape(-1,1)

In [14]:
print(y_np_col)

[[ 4]
 [ 8]
 [12]
 [16]
 [20]]


In [15]:
y_np_col.shape

(5, 1)

### Simplifying the variable names


In [16]:
X = x_np_col
Y = y_np_col

In [17]:
plt.plot(X,Y)

### Creating Linear regression object

In [54]:
model = LinearRegression()

### Training a model with datasets X and Y

In [55]:
model.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

### Predicting a value


In [56]:
model.predict(6)

array([[24.]])

In [42]:
x_np.shape

(5,)

### Calculated value of slope and intercept

In [58]:
m = model.coef_
c = model.intercept_
print("Slope(m) : ", m)
print("Intercept(c) : ", c)

Slope(m) :  [[4.]]
Intercept(c) :  [-3.55271368e-15]


### Testing a model with test data sets

In [59]:
test_x = np.array([7,8,9,10])


In [60]:
print(test_x)

[ 7  8  9 10]


In [62]:
test_y = m * test_x + c

In [63]:
print(test_y)

[[28. 32. 36. 40.]]
